site_name: WSS-RPC 
site_url: https://mydomain.org/wss-rpc
theme:
  name: material
markdown_extensions: 
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format